language: elixir
sudo: false
otp_release:
  - 20.1
elixir:
  - 1.5.1
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  #- mix credo --strict
  #- mix dialyzer --halt-exit-status
  - mix test
