language: elixir
sudo: required
otp_release:
  - 20.1
elixir:
  - 1.5.1
branches:
  only:
    - master
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
services:
  - docker

script:
  #- mix credo --strict
  #- mix dialyzer --halt-exit-status
  - mix test
