language: elixir
sudo: required
otp_release:
  - 20.3
  - 21.3
  - 22.1
elixir:
  - 1.8.2
  - 1.9.4
branches:
  only:
    - master
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
services:
  - docker

script:
  - mix lint
  - mix test
