language: elixir
sudo: required
otp_release:
  - 22.1.6
elixir:
  - 1.9.0
  - 1.9.1
  - 1.9.22
  - 1.9.3
  - 1.9.4
branches:
  only:
    - master
env:
  global:
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
services:
  - docker

script:
  - mix lint
  - mix test
