version: 2
general:
  artifacts:
    - "cover/excoveralls.html"

jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.1
        environment:
          MIX_ENV: test

    working_directory: ~/app

    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, compile
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "build"
      - save_cache:
          key: v1-build-cache
          paths: "build"

      - run: mix test

      - store_artifacts:
          path: cover/excoveralls.html
          destination: cover/excoveralls.html
